openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /events:
    post:
      operationId: postEvents
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/HealthDataEvent'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
        "202":
          description: Accepted
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        reason:
          type: string
        path:
          type: string
        method:
          type: string
        message:
          type: string
        timestamp:
          type: string
        status:
          type: integer
          format: int64
    HealthDataEvent:
      required:
      - eventId
      - timestamp
      type: object
      properties:
        eventId:
          type: string
        payload: {}
        dataType:
          type: string
        origin:
          type: string
        timestamp:
          type: string
