[package]
org = "tharmigan"
name = "simple_channel"
version = "0.1.0"
distribution = "2201.12.6"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "tharmigan"
name = "reliable.messaging"
version = "0.5.0"
repository = "local"
